name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - run: npm i -g pnpm@7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - run: bash build-tsc.sh ${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: bash build-typescript.sh ${{ github.event.inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git tag v${{ github.event.inputs.version }}
      - run: git push --tags
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: true
